#!/bin/bash

# Cài đặt curl nếu chưa có
if [ -f /etc/redhat-release ]; then
    if ! yum list installed curl &>/dev/null; then
        yum install -y curl
    fi
elif [ -f /etc/debian_version ]; then
    if ! dpkg -s curl &>/dev/null; then
        apt-get update
        apt-get install -y curl
    fi
else
    echo "Unsupported OS"
    exit 1
fi

# Cài đặt IPv6 cho CentOS 7
if [ -f /etc/redhat-release ]; then
    echo > /etc/sysctl.conf
    cat <<EOF >> /etc/sysctl.conf
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.all.disable_ipv6 = 0
EOF
    sysctl -p

    INTERFACE=$(ip route get 8.8.8.8 | awk 'NR==1 {print $5}')
    IP=$(ip -4 addr show $INTERFACE | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
    IPV6_PREFIX="2403:6a40:0:40"
    IPV6_ADDRESS="$IP::1/64"
    IPV6_GATEWAY="$IPV6_PREFIX::1"

    cat <<EOF >> /etc/sysconfig/network-scripts/ifcfg-$INTERFACE
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6ADDR=$IPV6_ADDRESS
IPV6_DEFAULTGW=$IPV6_GATEWAY
EOF

    service network restart
fi

# Cài đặt IPv6 cho Ubuntu
if [ -f /etc/lsb-release ]; then
    IPV4=$(curl -4 -s icanhazip.com)
    INTERFACE=$(ip route get 8.8.8.8 | awk 'NR==1 {print $5}')
    IPC=$(echo $IPV4 | cut -d"." -f3)
    IPD=$(echo $IPV4 | cut -d"." -f4)

    if [ "$IPC" = "4" ]; then
        IPV6_ADDRESS="2403:6a40:0:40::$IPD:0000/64"
        GATEWAY="2403:6a40:0:40::1"
    elif [ "$IPC" = "5" ]; then
        IPV6_ADDRESS="2403:6a40:0:41::$IPD:0000/64"
        GATEWAY="2403:6a40:0:41::1"
    elif [ "$IPC" = "244" ]; then
        IPV6_ADDRESS="2403:6a40:2000:244::$IPD:0000/64"
        GATEWAY="2403:6a40:2000:244::1"
    else
        IPV6_ADDRESS="2403:6a40:0:$IPC::$IPD:0000/64"
        GATEWAY="2403:6a40:0:$IPC::1"
    fi

    cat <<EOF >> /etc/netplan/99-netcfg-vmware.yaml
network:
  version: 2
  ethernets:
    $INTERFACE:
      dhcp4: true
      addresses:
        - $IPV6_ADDRESS
      gateway6: $GATEWAY
      nameservers:
        addresses:
          - 8.8.8.8
          - 2001:4860:4860::8888
EOF
    netplan apply
fi

# Hàm tạo chuỗi ngẫu nhiên
random() {
    tr </dev/urandom -dc A-Za-z0-9 | head -c5
    echo
}

# Mảng các ký tự hexa
array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)

# Hàm tạo địa chỉ IPv6 ngẫu nhiên
gen64() {
    ip64() {
        echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
    }
    echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
}

# Cài đặt 3proxy
echo "installing 3proxy"
URL="https://github.com/z3APA3A/3proxy/archive/refs/tags/0.9.3.tar.gz"
wget -qO- $URL | bsdtar -xvf-
cd 3proxy-0.9.3
make -f Makefile.Linux
mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
cp src/3proxy /usr/local/etc/3proxy/bin/

# Hàm tạo file cấu hình cho 3proxy
gen_3proxy() {
    cat <<EOF
daemon
maxconn 5000
nserver 1.1.1.1
nserver 8.8.4.4
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
stacksize 6291456 
flush
auth none
authcache 86400
allow 14.224.163.75
allow 127.0.0.1

$(awk -F "/" '{print "\n" \
"allow *" $1 "\n" \
"proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" \
"flush\n"}' ${WORKDATA})
EOF
}

# Hàm tạo file proxy cho người dùng
gen_proxy_file_for_user() {
    cat >proxy.txt <<EOF
$(awk -F "/" '{print $3 ":" $4}' ${WORKDATA})
EOF
}

# Hàm tạo dữ liệu
gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "//$IP4/$port/$(gen64 $IP6)"
    done
}

# Hàm tạo iptables
gen_iptables() {
    cat <<EOF
$(awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA}) 
EOF
}

# Hàm tạo ifconfig
gen_ifconfig() {
    cat <<EOF
$(awk -F "/" '{print "ifconfig $INTERFACE inet6 add " $5 "/64"}' ${WORKDATA})
EOF
}

# Tải file proxy
download_proxy() {
    cd $WORKDIR || return
    curl -F "file=@proxy.txt" https://file.io >> $LOGFILE 2>&1 || { echo "Failed to upload proxy file"; exit 1; }
}

# Tạo file rc.local để khởi động các dịch vụ cần thiết khi máy khởi động
cat << EOF > /etc/rc.d/rc.local
#!/bin/bash
touch /var/lock/subsys/local
EOF

# Cài đặt các gói cần thiết và thiết lập proxy
echo "Installing necessary packages and setting up proxy"
yum -y install wget gcc net-tools bsdtar zip >/dev/null

# Tạo thư mục làm việc và xác định IP
WORKDIR="/home/proxy"
WORKDATA="${WORKDIR}/data.txt"
mkdir -p $WORKDIR && cd $WORKDIR

IP4=$(curl -4 -s icanhazip.com)
IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')

echo "Internal IP = ${IP4}, External sub for IP6 = ${IP6}"
FIRST_PORT=39000
LAST_PORT=43000

echo "Cổng proxy: $FIRST_PORT"
echo "Số lượng proxy tạo: $(($LAST_PORT - $FIRST_PORT + 1))"

# Tạo dữ liệu cấu hình
gen_data >$WORKDIR/data.txt
gen_iptables >$WORKDIR/boot_iptables.sh
gen_ifconfig >$WORKDIR/boot_ifconfig.sh
chmod +x $WORKDIR/boot_*.sh /etc/rc.local

# Tạo file cấu hình cho 3proxy
gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

# Tạo file service cho 3proxy
cat <<EOF > /etc/systemd/system/3proxy.service
[Unit]
Description=3proxy Proxy Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
Restart=always

[Install]
WantedBy=multi-user.target

# Tạo và khởi động dịch vụ 3proxy
systemctl daemon-reload
systemctl enable 3proxy
systemctl start 3proxy

# Thêm lệnh vào rc.local để khởi động proxy khi hệ thống bắt đầu
cat >>/etc/rc.local <<EOF
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -u unlimited -n 999999 -s 16384
/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
EOF

# Đảm bảo rc.local có quyền thực thi và khởi động nó
chmod 755 /etc/rc.local
bash /etc/rc.local

# Xóa thư mục tạm thời
rm -rf /root/3proxy-0.9.3
rm -rf setup

# Tạo file proxy cho người dùng
gen_proxy_file_for_user

echo "Proxy đã được bật"

echo "Tổng số địa chỉ IPv6 hiện tại:"
ip -6 addr | grep inet6 | wc -l

# Tải file proxy
download_proxy
