#!/bin/bash

# Set up 3proxy
echo "Setting up 3proxy..."
wget --no-check-certificate https://github.com/z3APA3A/3proxy/archive/0.9.3.tar.gz
tar -xzf 0.9.3.tar.gz
cd 3proxy-0.9.3
make -f Makefile.Linux
sudo make -f Makefile.Linux install
cd $WORKDIR

# Function to generate 3proxy configuration
gen_3proxy() {
    cat <<EOF
daemon
maxconn 5000
nserver 1.1.1.1
nserver 8.8.4.4
nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
stacksize 6291456 
flush
auth none
authcache 86400
allow 14.224.163.75
allow 127.0.0.1

$(awk -F "/" '{print "\n" \
"allow *" $1 "\n" \
"proxy -n -a -p" $4 " -i\$INTERFACE -e"$5" -t127.0.0.1 -T9050\n" \
"flush\n"}' ${WORKDATA})
EOF
}

# Function to generate proxy file for user
gen_proxy_file_for_user() {
    cat >proxy.txt <<EOF
$(awk -F "/" '{print $3 ":" $4}' ${WORKDATA})
EOF
}

# Function to generate data
gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "//$IPv4/$port/127.0.0.1:9050"
    done
}

# Function to generate iptables rules
gen_iptables() {
    awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $4 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA}
}

# Function to generate ifconfig commands
gen_ifconfig() {
    awk -F "/" '{print "ifconfig \$INTERFACE inet add " $5 "/24"}' ${WORKDATA}
}

# Set up working directory and determine IP
WORKDIR="/home/proxy"
WORKDATA="${WORKDIR}/data.txt"
mkdir -p $WORKDIR && cd $WORKDIR || exit

IPv4=$(curl -4 -s ifconfig.co)
echo "IPv4 address: $IPv4"

FIRST_PORT=10000
LAST_PORT=11000

echo "Proxy Ports: $FIRST_PORT-$LAST_PORT"

# Generate configuration data
gen_data >$WORKDATA
gen_iptables >$WORKDIR/boot_iptables.sh
gen_ifconfig >$WORKDIR/boot_ifconfig.sh
chmod +x $WORKDIR/boot_*.sh /etc/rc.local

# Generate 3proxy configuration file
gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

# Set up 3proxy service
cat <<EOF | sudo tee /etc/systemd/system/3proxy.service
[Unit]
Description=3proxy Proxy Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and start 3proxy service
sudo systemctl daemon-reload
sudo systemctl enable 3proxy
sudo systemctl start 3proxy

# Add proxy startup commands to rc.local
cat >>/etc/rc.local <<EOF
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -u unlimited -n 999999 -s 16384
/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg
EOF

# Ensure rc.local can be executed and start it
sudo chmod 755 /etc/rc.local
sudo bash /etc/rc.local

# Generate proxy file for user
gen_proxy_file_for_user

echo "Proxy server setup complete."
